retina_grader/urls.py
from django.urls import path

from . import views

urlpatterns = [
 	path('', views.index, name='index'),
 	path('index_json/', views.index_json, name='index_json'),

    path('detail/', views.detail, name='detail'),
	path('data_export/', views.data_export, name='data_export'),
    path('new_files/', views.new_files, name='new_files'),
    path('get_image/', views.get_image, name='get_image'),
	path('detect_bones/', views.detect_bones, name='detect_bones'),
	path('detect_osteo/', views.detect_osteo, name='detect_osteo'),

]

simple_grader/urls.py
# from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import  static
from django.contrib.auth.views import auth_login , auth_logout
from django.contrib import admin




urlpatterns = [
    path('admin/', admin.site.urls),
    path('sianno/', include('retina_grader.urls')),
    path('accounts/', admin.site.urls),
    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

retina_grader/models.py
from re import X
import uuid

from django.forms.widgets import DateInput
from django.db import models
from django.contrib.auth.models import User

from django.core.files.storage import FileSystemStorage
from django.conf import settings


GRADING_STATUS_CHOICES = (
('Inactive','Inactive'),
('Active','Active'),

)
#This is a different comment than main branch

#DOCUMENT TYPES
DOCUMENT_TYPES = (('BITEWING','BITEWING'),
				 ('PANAROMIC','PANAROMIC'),
				
					)


#PURPOSE TYPES
PURPOSE_TYPES = (('SCREENING','SCREENING'),
				 ('GRADING','GRADING'),
				
					)
#UI types
UI_CONTROL_TYPES = (('Label','Label'),
				 ('Radio','Radio'),
				 ('CheckBox','CheckBox'),
				 ('Text','Text'),
				 ('Select','Select'),
				 ('Date','Date'),
					('number','number'),
					('TextArea', 'TextArea'),

					)

VALUE_SET_CHOICES = (
	('Yes','Yes'),
	('No','No'),
	('Type I','Type I'),
	('Type II','Type II'),
	('Gestational','Gestational'),
	('Other','Other'),
	('Smoker','Smoker'),
	('Ex Smoker','Ex Smoker'),
	('Non Smoker','Non Smoker'),
	('Diabetic Laser','Diabetic Laser'),
	('Other Ocular Laser','Other Ocular Laser'),
	('No Laser', 'No Laser'),

	('6/60','6/60'),
	('6/36','6/36'),
	('6/24','6/24'),
	('6/18','6/18'),
	('6/9','6/9'),
	('6/6','6/6'),
	('6/5','6/5'),
	('CF','CF'),
	('HM','HM'),
	('LP','LP'),
	('NLP','NLP'),

	('Mild NPDR','Mild NPDR'),#DR
	('Moderate NPDR','Moderate NPDR'),#DR
	('Severe NPDR','Severe NPDR'),#DR
	('PDR','PDR'),#DR
	('No DR','No DR'),#DR
	('Unable to grade','Unable to grade'),#DR
	('Present','Present'), #DMO
	('None','None'), #DMO

	('Repeat photos in 24 months','Repeat photos in 2 years'),#Recommendation
	('Repeat photos in 1 year','Repeat photos in 1 year'),#Recommendation
	('Repeat photos in 6 months','Repeat photos in 6 months'),#Recommendation

	('Review in clinic','Review in clinic'),#Recommendation

	('Not Applicable','Not Applicable'),#Not applicable for other items

	('1 Week','1 Week'),
	('1 Month','1 Month'),
	('3 Months','3 Months'),
	('1 Year','1 Year'),

	('Not Recorded','Not Recorded'),
	('Left','Left'),
	('Right', 'Right'),

	('Good', 'Good'),
	('Poor', 'Poor'),
	('Moderate', 'Moderate'),

	('Correct', 'Correct'),
	('Incorrect', 'Incorrect'),	

	#Diabetic Foot XRAY types
	#Body Parts

	('Ankle', 'Ankle'),	
	('Foot', 'Foot'),	
	('Forefoot', 'Forefoot'),	
	('Other', 'Other'),
#View Types

('DP','DP'),
('Obl','Obl'),
('Lat','Lat'),



)

#store the image under user's name
def get_file_location_path(instance, filename):
	print("FILE LOCATION: " + 'document_tray/{0}/{1}'.format(instance.allocated_to.username, filename))	
	return 'document_tray/{0}/{1}'.format(instance.allocated_to.username, filename)


# Create your models here.
class GradingType(models.Model):
	"""
	Model to hold grading history types. These are collection of predefined grading fields set by the administrator
	Each of these types can be of different user interface control types : eg: L/R is a is a drop down.
	"""

	#id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

	text = models.CharField(max_length=200)
	ui_control_type = models.CharField( max_length = 20,  default = "Text", choices = UI_CONTROL_TYPES)
	ui_order = models.IntegerField(default=0) #ordering field which manages the user interface order

	#options = models.CharField( max_length = 300, default = "")#Semicolon seperated values based


	def __str__(self):
		return "%s" % (self.text)



class GradingField(models.Model):
	"""
	Model to hold grading field. Eg  a grading field which is of a gradig type and with

	"""
	#id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

	grading_type = models.ForeignKey(GradingType, on_delete = models.CASCADE)
	comments =  models.CharField(max_length = 100, default="admin comment")
	is_monitorred = models.BooleanField(default= False)
	default_value = models.CharField(max_length = 100, default="admin comment")
	def __str__(self):
		return "%s" % (self.grading_type)

class Document(models.Model):
	"""Model to hold the actual document.
	"""
	# document = models.FileField(upload_to="document_tray/")
	type = models.CharField(max_length = 20, blank=True, null=True, choices=DOCUMENT_TYPES)
	width = models.PositiveIntegerField(blank=True, null=True)
	height = models.PositiveIntegerField(blank=True, null=True)

	scale = models.DecimalField(max_digits=16, decimal_places=12, default=1.0)
	document = models.FileField(blank=True, null=True,
		# height_field='height',
		# width_field='width',
		storage=FileSystemStorage(location=settings.MEDIA_ROOT),
		upload_to=get_file_location_path)

	status =  models.CharField(max_length = 20, default="Draft")
	allocated_to = models.ForeignKey(User, on_delete = models.CASCADE, null=True )
	random_id =  models.CharField(max_length = 20, default="UNASSIGNED")
	purpose =  models.CharField(max_length = 20, blank=True, null=True, choices=PURPOSE_TYPES)
	date_added = models.DateTimeField(null=True, auto_now_add=True)
	date_modified = models.DateTimeField(null=True, auto_now=True)

	#Additional information regarding patient
	patient_id = models.CharField(max_length = 20, default="UNASSIGNED")#patient ID
	accession_no = models.CharField(max_length = 100, default="UNASSIGNED")#accession number
	view_position =  models.CharField(max_length = 100, default="UNASSIGNED")#accession number
	anatomy = models.CharField(max_length = 100, default="Not Available")#anatomy
	class Meta:
		if settings.USE_RANDOM_ID : 
			ordering = ['random_id']

		else:
			ordering = ['document']

	def __str__(self):
		if settings.USE_RANDOM_ID : 
			return "ID: %s | Allocated To: %s | Status: %s" % (self.random_id, self.allocated_to, self.status)
		else:
			return "ID: %s | Allocated To: %s | Status: %s" % (self.document.name, self.allocated_to, self.status)

class Rectangle(models.Model):
	document = models.ForeignKey(Document, on_delete = models.CASCADE)
	r_id = models.PositiveIntegerField(null=True, blank=True)
	x = models.FloatField(null=True, blank=True)
	y = models.FloatField(null=True, blank=True)
	width = models.FloatField(null=True, blank=True)
	height = models.FloatField(null=True, blank=True)
	'''
	tooth = models.TextField(null=True, blank=True, default = "unknown")
	site = models.CharField(max_length = 200, verbose_name = "Site of Caries", default = "Occlusal", blank = True, null=True)
	depth = models.CharField(max_length = 200, verbose_name = "Depth of Caries", default = "Enamel up to DEJ", blank = True, null=True)
	eruption = models.CharField(max_length = 200, verbose_name = "Eruption Status", default = "Erupted", blank = True, null=True)
	Supernumerary = models.CharField(max_length = 200, verbose_name = "Supernumerary Tooth", default = "None", blank = True, null=True)'''

	#fields for wrist xray
	bone_number = models.CharField(max_length=50,null=True, blank=True, default = "unknown")
	fracture_on_current_view = models.CharField(max_length=20,null=True, blank=True, default = "No")
	fracture_on_other_view = models.CharField(max_length=20,null=True, blank=True, default = "No")
	view_type = models.CharField(max_length=20,null=True, blank=True, default = "unknown")

	#firled for foot xray
	annotation_type = models.CharField(max_length=50,null=True, blank=True, default = "unknown")
	toe_number = models.CharField(max_length=250,null=True, blank=True, default = "unknown")
	#field for adding osteomyelitis score
	osteomyelitis_present_score = models.FloatField(default = 0.0)




# a polygon attached to a document object via ForeignKey.  In case of multiple polygons, the point coordinates are
# stored in seperate class, Point
class Polygon(models.Model):
	document = models.ForeignKey(Document, on_delete=models.CASCADE)
	idx = models.IntegerField(null=True,blank=True)

	#fields for wrist xray
	bone_number = models.CharField(max_length=50,null=True, blank=True, default = "unknown")
	fracture_on_current_view = models.CharField(max_length=20,null=True, blank=True, default = "No")
	fracture_on_other_view = models.CharField(max_length=20,null=True, blank=True, default = "No")
	view_type = models.CharField(max_length=20,null=True, blank=True, default = "unknown")
	
# polygon point - with Polygon FK
class Point(models.Model):
	polygon = models.ForeignKey(Polygon, on_delete=models.CASCADE)
	x = models.FloatField(null=True, blank=True)
	y = models.FloatField(null=True, blank=True)
	idx = models.IntegerField(null=True, blank=True)

class Grading(models.Model):
	"""
	Model to hold the actual Grading. This binds the grading to the document and other details. This field and will hold values.

	"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)


	grading_field = models.ForeignKey(GradingField, on_delete = models.CASCADE)
	document = models.ForeignKey(Document, on_delete = models.CASCADE)
	date = models.DateField(verbose_name="Date of onset", blank=True, null=True)#start date of the onset
	value = models.CharField(max_length=200 ,verbose_name="Observed values (if any)", blank=True, null= True, default = "Not Recorded")

	class Meta:
		ordering = ['-grading_field__grading_type__ui_order']#set the ordering field to this


class GradingValueSet(models.Model):
	"""

	Model to hold values for each grading for the grading type.
	Each medical history type can have possible values. Eg: Diabetic Type should have Type1, TypeII as values


	"""
	#id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

	grading_type = models.ForeignKey(GradingType, on_delete = models.CASCADE)
	value = models.CharField(max_length=200, choices = VALUE_SET_CHOICES)



class GlobalSettings(models.Model):
	key =  models.CharField(max_length = 100)
	value = models.CharField(max_length=500)

retina_grader/templates/detail.html
{% load template_tags %}

{% load static %}
<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/sianno.css' %}" />
 
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <script src="/static/js/jquery.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.css' %}">
  <link rel="icon" href="data:;base64,iVBORw0KGgo=">

</head>
<script type="text/javascript">
  var width = "{{doc.width}}",
    height =  "{{doc.height}}",
    type = "{{doc.type}}",
    scale = "{{doc.scale}}";
    // url = "/media/{{ doc.document.name }}";
    url = "/sianno/get_image/?document_id={{ doc.id }}";
    document_id = "{{ doc.id }}";
    osteomyelitis_present_score_visualisation_feature_enabled = false;//additional visualisation feature for osteo detection. Disabled by default so that all the data is viewable. If enabled, user has to press d key to show all the rectangles. else, it will show only the ones above 50%
    var osteomyelitis_present_score_visualisation = false;//osteomyelitis_present_score_visualisation handles the visualisation of the detected osteo  scores



  // var this_page = "{{this_page}}";
</script>
{% if user.username == "osteo_labeler1" %}
<script>
osteomyelitis_present_score_visualisation_feature_enabled = true;
osteomyelitis_present_score_visualisation = true;


</script>
{% endif %}

{% if annotation == "rect-foot" %}
<script src="/static/js/d3.v4.min.js"></script>
{% elif annotation == "poly" %}
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://unpkg.com/d3-moveto" ></script>
<script src="https://cdn.jsdelivr.net/d3js/3.5.9/d3.min.js"></script>
{% endif %}
<body style="background-color: black; color: white">
  <nav class="navbar navbar-expand navbar-light bg-light">
    <a class="navbar-brand" href="/sianno/">
        <img src="{% static 'images/CSIRO_logo.png' %}" width="30" height="30" alt="">

        CSIRO SIANNO (<b>S</b>imple <b>I</b>mage <b>ANNO</b>tation Tool)
    </a>


    <span  class="navbar-text">Image Review Progress for {{user.username}}: {{ completed_count }} of {{ total_count }} Image(s)</span>
    
    <span class="navbar-text"><progress value="{{ completed_count }}" max="{{ total_count }}"> </progress></span>
    

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse " id="navbarNavDropdown">
            <ul class="navbar-nav  ml-auto">

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Actions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user|is_in_group:"coordinator" == True %}
            <a class="dropdown-item" href="/sianno/data_export/">
                <span class="oi oi-data-transfer-download"></span> CSV</a>

            <button type="button" class="dropdown-item" id="btn_upload">
                <span class="oi oi-cloud-upload"></span> Upload </button>
              <button type="button" class="dropdown-item" id="btn_detect_bones">
                  <span class="oi oi-cpu"></span> Detect Bones on Draft </button>
                  
            {% endif %}
            <a class="dropdown-item" href="/accounts/logout/?next=/sianno/"> <span
                    class="oi oi-account-logout"></span> Logout </a>
        
        </div>
    </li>

    </ul>
    </div>

</nav>


<a class="btn btn-warning" href="/sianno/">
  <span class="oi oi-arrow-circle-left"></span> Back
</a>
<label style="color: orange;" id="id-label-ui-info"></label>
{% if annotation == "poly" %}
<button class="btn btn-warning annotation_button" href="/sianno/" data-key-pressed-id = "1">
  Draw Polygon
</button>
<button id="btn_delete_selected" class="btn btn-warning" href="/sianno/">
<span class="oi oi-delete"></span> Delete Selected
</button>
{% endif %}
<!-- {% if annotation == "rect-foot" %}
<button class="btn btn-primary annotation_button" href="/sianno/" data-key-pressed-id = "1">
  Draw Osteomyelitis
</button>
<button class="btn btn-success annotation_button" href="/sianno/" data-key-pressed-id = "2">
  Draw Lis Franc
</button>
<button class="btn btn-secondary annotation_button" href="/sianno/" data-key-pressed-id = "3">
  Draw Rocker bottom foot
</button>
<button class="btn btn-info annotation_button" href="/sianno/" data-key-pressed-id = "4">
  Draw Skin ulcer
</button>
<button id="btn_delete_selected" class="btn btn-danger" href="/sianno/">
<span class="oi oi-delete"></span> Delete Selected
</button>
{% endif %} -->

<div class="row">




{% if doc.purpose == "GRADING" and doc.type == "WRIST-XRAY" %}


<label>Accession Number: {{doc.accession_no}}</label>  
<label>View Type: {{ doc.view_position}}</label>

<div class="col-sm-9" id="imageBody-WX">
    
</div>
{% endif %}

{% if doc.purpose == "GRADING" and doc.type == "FOOT-XRAY" %}


<div class="col-sm-9"  id="imageBody-FX">
    
</div>
{% endif %}

<br>

{% if doc.purpose == "GRADING" and doc.type == "WRIST-XRAY" %}
<div class="col-sm-3 card text-left" > 
  <div class="card-body">
    <form method="post" id="form-wrist-xray-grading" >
      {% csrf_token %}
      <input type="hidden" name="save_next_wrist_xray" value="yes">
      <label class="btn btn-danger">
        <input type="checkbox" name= "exclude_accession_number"/>
          Exclude this Accession Number
      </label>
  <label>Click Save & Next to go to next image. Rectangles and annotation data are automatically saved.</label>
      <button type="button" id="id_btn_save_next" class="btn btn-primary float-right">Save & Next</button>
      </form>
  </div>
 
</div>

{% endif %}

{% if doc.purpose == "GRADING" and doc.type == "FOOT-XRAY" %}
<div class="col-sm-3 card text-left" style="color: black; padding:10px"> 
  
  <div class="card-body">

  
  <form method="post" id="form-next-foot-grading" class="form" >
    {% csrf_token %}
    <input type="hidden" name="save_next_foot_xray" value="yes">
    <label class="label label-info" >Accession Number: {{doc.accession_no}}</label>
    <label class="label label-info" >View Position: {{doc.view_position}}</label>
    <label class="label label-info" >Anatomy: {{doc.anatomy}}</label>

    <label class="btn btn-danger">
      <input type="checkbox" name= "exclude_accession_number"/>
        Exclude this Accession Number
    </label>

    {% for g in doc.grading_set.all %}
    {% if  g.grading_field.grading_type.ui_control_type == "Radio"  %}
   <!-- <fieldset> -->
    <h5>{{ g.grading_field.grading_type }}</h5>

    <div class="btn-group btn-group-toggle" data-toggle="buttons">


         {% for item in g.grading_field.grading_type.gradingvalueset_set.all %}


                               
                                <label for = "grading_{{g.id}}_{{g.grading_field}}_{{ item.id}}" class="btn btn-success" >   <input
                                  required
                                  id = "grading_{{g.id}}_{{g.grading_field}}_{{ item.id}}"
                                  type="radio"
                                     name="grading_{{g.id}}"
                                     value="{{ item.value }}"
                              {% if g.value == item.value %}
                                     checked="checked"
                              {% endif %}
                              />
                              {{ item.value }}</label>

                                

                            {% endfor %}


                                </div>

<!-- </fieldset> -->
    {% elif g.grading_field.grading_type.ui_control_type == "TextArea" %}
        <fieldset>
        <legend>{{ g.grading_field.grading_type }}:</legend>



        <textarea cols="200" rows="5", name="grading_{{g.id}}", id="grading_{{g.id}}">{{ g.value }}</textarea>
        </fieldset>
    {% endif %}
{% endfor  %}




<label>Click Save & Next to go to next image. Rectangles and annotation data are automatically saved.</label>
    <br>
    <br>
    <!-- <button type="button" id="id_btn_run_osteomyelitis_detection" class="btn btn-warning float-right">Detect Osteomyelitis</button>
    <br>
    <br>     -->
    <button type="button" id="id_btn_save_next_foot" class="btn btn-primary float-right">Save & Next</button>
    

    </form>
    </div>
</div>

{% endif %}

</div>
<div class="container-fluid">
      <div class="row">
        {% include "modals/wrist_xray_modal.html" %}
        {% include "modals/foot_xray_modal.html" %}
        
      </div>
</div>

</body>

{% if annotation == "rect" %}
<script type="text/javascript" src="{% static 'js/wrist_annotation.js' %}"></script>
{% elif annotation == "rect-foot" %}
<script type="text/javascript" src="{% static 'js/foot_annotation.js' %}"></script>
{% elif annotation == "poly" %}
<script type="text/javascript" src="{% static 'js/polygon_annotation.js' %}"></script>
{% endif %}

retina_grader/templates/index.html
{% load template_tags %}
{% load static %}

<head>
    <script src="/static/js/moment.min.js"></script>
    <script type="text/javascript" src="{% static 'js/moment-timezone-with-data.js' %}"></script>

    <link href="/static/css/tabulator_modern.min.css" rel="stylesheet">
    <script type="text/javascript" src="/static/js/tabulator.min.js"></script>


    <script src="/static/js/jquery.min.js"></script>

    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">

    <script src="/static/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.css' %}">


</head>

<!--  -->


<body class="container-fluid">

    <nav class="navbar navbar-expand">
        <a class="navbar-brand" href="/sianno/">
            <img src="{% static 'images/CSIRO_logo.png' %}" width="30" height="30" alt="">

            CSIRO SIANNO (<b>S</b>imple <b>I</b>mage <b>ANNO</b>tation Tool)
        </a>


        

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse " id="navbarNavDropdown">
                <ul class="navbar-nav  ml-auto">

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                Actions
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if user|is_in_group:"coordinator" == True %}
                <a class="dropdown-item" href="/sianno/data_export/">
                    <span class="oi oi-data-transfer-download"></span> CSV</a>

                <button type="button" class="dropdown-item" id="btn_upload">
                    <span class="oi oi-cloud-upload"></span> Upload </button>
                    <button type="button" class="dropdown-item" id="btn_detect_bones">
                        <span class="oi oi-eye"></span> Detect Bones on Draft </button>
                        <button type="button" class="dropdown-item" id="btn_detect_osteo">
                            <span class="oi oi-eye"></span> Detect Osteo </button>
                {% endif %}
                <a class="dropdown-item" href="/accounts/logout/?next=/sianno/"> <span
                        class="oi oi-account-logout"></span> Logout </a>

            
            </div>
        </li>

        </ul>
        </div>

    </nav>

    <div class="row">

        <div class="col-sm-12">
            <h1>
                WorkList for {{ user.first_name }} {{ user.last_name }} </h1>

 
                <label class="label label-default">Total Progress {{ completed_count }} of {{ total_count }} Images</label><br>
                <progress style="width: 100%" value="{{ completed_count }}" max="{{ total_count }}"> </progress>



            <!-- <table id="id_table_worklist">

                <thead>
                    <tr>
                        <th>ID</th>
                        <th tabulator-field="Status">Status</th>
                        {% if user|is_in_group:"coordinator" == True %}

                        <th>User</th>

                        {%endif%}
                        <th>Purpose</th>
                        <th>Type</th>
                        <th tabulator-formatter='datetime' tabulator-formatterParams_outputFormat="DD/MM/YY">Date
                            Modified</th>

                    </tr>
                </thead>

                <tbody>
                    {% for doc in document_list %}

                    <tr class="clickable-row" data-href="/sianno/detail/?d={{ doc.id }}">
                        <td>{{doc.id}}</td>
                        <td>{{doc.status}}</td>
                        {% if user|is_in_group:"coordinator" == True %}

                        <td> {{doc.allocated_to.username}}</td>
                        {% endif %}
                        <td>{{doc.purpose|lower}}</td>
                        <td>{{doc.type|lower}}</td>
                        <td>{{doc.date_modified|date:'c'}}</td>

                    </tr>
                    {%  endfor %}

                </tbody>
            </table> -->







</table>


<ul class="nav nav-pills" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#draft_content">Drafts</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#reviewed_content">Reviewed</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#draft_bone_detected">Draft_Bone_Detected</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#draft_osteo_detected">Draft_Osteo_Detected</a>
      </li>
  </ul>



  <div class="tab-content" id = "tab_content">
    <div class="tab-pane fade show active" id = "draft_content"><div id= "id_table_worklist_draft"  ></div>
          
    </div>
          
    <div class="tab-pane fade" id = "reviewed_content"><div id= "id_table_worklist_reviewed"  > </div>
        </div>

    <div class="tab-pane fade" id = "draft_bone_detected"> <div id= "id_table_draft_bone_detected"  ></div>
        </div>

        <div class="tab-pane fade" id = "draft_osteo_detected"> <div id= "id_table_draft_osteo_detected"  ></div>
    </div>
    
        </div> 
    </div>


    {% if user|is_in_group:"coordinator" == True %}
    <div id="uploadDiv"></div>
    {% endif %}

</body>